[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=-bulk-memory",
    "-C", "target-feature=-reference-types",
    "-C", "opt-level=z",
    "-C", "panic=abort",
]

[build]
target = "wasm32-unknown-unknown"
